//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace POETradeHelper.ItemSearch.Tests.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("POETradeHelper.ItemSearch.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Class: Active Skill Gems
        ///Rarity: Gem
        ///Flameblast
        ///--------
        ///Vaal, Spell, AoE, Fire, Channelling
        ///Level: 20 (Max)
        ///Mana Cost: 7
        ///Cast Time: 0.20 sec
        ///Critical Strike Chance: 5.00%
        ///Effectiveness of Added Damage: 60%
        ///Quality: +20% (augmented)
        ///Alternate Quality
        ///--------
        ///Requirements:
        ///Level: 70
        ///Int: 155
        ///--------
        ///Channels to build up a large explosion, which is released when you stop using the skill. The longer you channel, the larger the area of effect and damage of the explosion, up to 10 stages. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnomalousVaalFlameblast {
            get {
                return ResourceManager.GetString("AnomalousVaalFlameblast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Class: Active Skill Gems
        ///Rarity: Gem
        ///Purity of Lightning
        ///--------
        ///Aura, Vaal, Spell, AoE, Duration, Lightning
        ///Level: 1
        ///Reservation: 35% Mana
        ///Cooldown Time: 1.20 sec
        ///Cast Time: Instant
        ///--------
        ///Requirements:
        ///Level: 24
        ///Int: 58
        ///--------
        ///Casts an aura that grants lightning resistance to you and your allies.
        ///--------
        ///You and nearby allies gain 22% additional Lightning Resistance
        ///--------
        ///Vaal Impurity of Lightning
        ///--------
        ///Cooldown Time: 0.50 sec
        ///Souls Per Use: 50
        ///Can Store 1 Use
        ///Soul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VaalImpurityOfLightning {
            get {
                return ResourceManager.GetString("VaalImpurityOfLightning", resourceCulture);
            }
        }
    }
}
