//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POETradeHelper.ItemSearch.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POETradeHelper.ItemSearch.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Class: Skill Gems
        ///Rarity: Gem
        ///Animate Weapon of Ranged Arms
        ///--------
        ///Duration, Minion, Spell, Vaal, Physical
        ///Level: 20 (Max)
        ///Cost: 20 Mana
        ///Cast Time: 0.75 sec
        ///Quality: +20% (augmented)
        ///--------
        ///Requirements:
        ///Level: 70
        ///Dex: 98
        ///Int: 68
        ///--------
        ///Animates a Ranged Weapon Item or Lingering Blade to fight by your side. You cannot animate unidentified Weapons. Will not animate weapons with 6 sockets. Cannot be used by Traps or Mines.
        ///--------
        ///Base duration is 40.00 seconds
        ///Can use Items requ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VaalAnimateWeaponOfRangedArms {
            get {
                return ResourceManager.GetString("VaalAnimateWeaponOfRangedArms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Class: Active Skill Gems
        ///Rarity: Gem
        ///Purity of Lightning
        ///--------
        ///Aura, Vaal, Spell, AoE, Duration, Lightning
        ///Level: 1
        ///Reservation: 35% Mana
        ///Cooldown Time: 1.20 sec
        ///Cast Time: Instant
        ///--------
        ///Requirements:
        ///Level: 24
        ///Int: 58
        ///--------
        ///Casts an aura that grants lightning resistance to you and your allies.
        ///--------
        ///You and nearby allies gain 22% additional Lightning Resistance
        ///--------
        ///Vaal Impurity of Lightning
        ///--------
        ///Cooldown Time: 0.50 sec
        ///Souls Per Use: 50
        ///Can Store 1 Use
        ///Soul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VaalImpurityOfLightning {
            get {
                return ResourceManager.GetString("VaalImpurityOfLightning", resourceCulture);
            }
        }
    }
}
