<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac" />
        <PackageReference Include="Autofac.Extensions.DependencyInjection" />
        <PackageReference Include="Autofac.Extras.DynamicProxy" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
        <PackageReference Update="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Source\POETradeHelper.Common.Contract\POETradeHelper.Common.Contract.csproj" />
    </ItemGroup>

</Project>
