//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POETradeHelper.PathOfExileTradeApi.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POETradeHelper.PathOfExileTradeApi.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;result&quot;:[{&quot;id&quot;:&quot;Currency&quot;,&quot;label&quot;:&quot;Currency&quot;,&quot;entries&quot;:[{&quot;id&quot;:&quot;alt&quot;,&quot;text&quot;:&quot;Orb of Alteration&quot;,&quot;image&quot;:&quot;\/image\/Art\/2DItems\/Currency\/CurrencyRerollMagic.png?v=6d9520174f6643e502da336e76b730d3&quot;},{&quot;id&quot;:&quot;fuse&quot;,&quot;text&quot;:&quot;Orb of Fusing&quot;,&quot;image&quot;:&quot;\/image\/Art\/2DItems\/Currency\/CurrencyRerollSocketLinks.png?v=0ad7134a62e5c45e4f8bc8a44b95540f&quot;},{&quot;id&quot;:&quot;alch&quot;,&quot;text&quot;:&quot;Orb of Alchemy&quot;,&quot;image&quot;:&quot;\/image\/Art\/2DItems\/Currency\/CurrencyUpgradeToRare.png?v=89c110be97333995522c7b2c29cae728&quot;},{&quot;id&quot;:&quot;chaos&quot;,&quot;text&quot;:&quot;Cha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StaticDataJson {
            get {
                return ResourceManager.GetString("StaticDataJson", resourceCulture);
            }
        }
    }
}
