//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POETradeHelper.ItemSearch.Contract.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POETradeHelper.ItemSearch.Contract.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (augmented).
        /// </summary>
        public static string AugmentedDescriptor {
            get {
                return ResourceManager.GetString("AugmentedDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted.
        /// </summary>
        public static string CorruptedDescriptor {
            get {
                return ResourceManager.GetString("CorruptedDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string ItemRarityCurrency {
            get {
                return ResourceManager.GetString("ItemRarityCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divination Card.
        /// </summary>
        public static string ItemRarityDiviniationCard {
            get {
                return ResourceManager.GetString("ItemRarityDiviniationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gem.
        /// </summary>
        public static string ItemRarityGem {
            get {
                return ResourceManager.GetString("ItemRarityGem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic.
        /// </summary>
        public static string ItemRarityMagic {
            get {
                return ResourceManager.GetString("ItemRarityMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string ItemRarityNormal {
            get {
                return ResourceManager.GetString("ItemRarityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        public static string ItemRarityRare {
            get {
                return ResourceManager.GetString("ItemRarityRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string ItemRarityUnique {
            get {
                return ResourceManager.GetString("ItemRarityUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string LevelDescriptor {
            get {
                return ResourceManager.GetString("LevelDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality:.
        /// </summary>
        public static string QualityDescriptor {
            get {
                return ResourceManager.GetString("QualityDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity:.
        /// </summary>
        public static string RarityDescriptor {
            get {
                return ResourceManager.GetString("RarityDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements:.
        /// </summary>
        public static string RequirementsDescriptor {
            get {
                return ResourceManager.GetString("RequirementsDescriptor", resourceCulture);
            }
        }
    }
}
