//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POETradeHelper.ItemSearch.Contract.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POETradeHelper.ItemSearch.Contract.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (augmented).
        /// </summary>
        public static string AugmentedDescriptor {
            get {
                return ResourceManager.GetString("AugmentedDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blighted.
        /// </summary>
        public static string BlightedPrefix {
            get {
                return ResourceManager.GetString("BlightedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted.
        /// </summary>
        public static string CorruptedKeyword {
            get {
                return ResourceManager.GetString("CorruptedKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crusader Item.
        /// </summary>
        public static string CrusaderItem {
            get {
                return ResourceManager.GetString("CrusaderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elder Item.
        /// </summary>
        public static string ElderItem {
            get {
                return ResourceManager.GetString("ElderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience:.
        /// </summary>
        public static string ExperienceDescriptor {
            get {
                return ResourceManager.GetString("ExperienceDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flask.
        /// </summary>
        public static string FlaskKeyword {
            get {
                return ResourceManager.GetString("FlaskKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter Item.
        /// </summary>
        public static string HunterItem {
            get {
                return ResourceManager.GetString("HunterItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Level:.
        /// </summary>
        public static string ItemLevelDescriptor {
            get {
                return ResourceManager.GetString("ItemLevelDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Quantity:.
        /// </summary>
        public static string ItemQuantityDescriptor {
            get {
                return ResourceManager.GetString("ItemQuantityDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string ItemRarityCurrency {
            get {
                return ResourceManager.GetString("ItemRarityCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Rarity:.
        /// </summary>
        public static string ItemRarityDescriptor {
            get {
                return ResourceManager.GetString("ItemRarityDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divination Card.
        /// </summary>
        public static string ItemRarityDiviniationCard {
            get {
                return ResourceManager.GetString("ItemRarityDiviniationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gem.
        /// </summary>
        public static string ItemRarityGem {
            get {
                return ResourceManager.GetString("ItemRarityGem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic.
        /// </summary>
        public static string ItemRarityMagic {
            get {
                return ResourceManager.GetString("ItemRarityMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string ItemRarityNormal {
            get {
                return ResourceManager.GetString("ItemRarityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        public static string ItemRarityRare {
            get {
                return ResourceManager.GetString("ItemRarityRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string ItemRarityUnique {
            get {
                return ResourceManager.GetString("ItemRarityUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string LevelDescriptor {
            get {
                return ResourceManager.GetString("LevelDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Flask.
        /// </summary>
        public static string LifeFlaskKeyword {
            get {
                return ResourceManager.GetString("LifeFlaskKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana Flask.
        /// </summary>
        public static string ManaFlaskKeyword {
            get {
                return ResourceManager.GetString("ManaFlaskKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Tier:.
        /// </summary>
        public static string MapTierDescriptor {
            get {
                return ResourceManager.GetString("MapTierDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Pack Size:.
        /// </summary>
        public static string MonsterPackSizeDescriptor {
            get {
                return ResourceManager.GetString("MonsterPackSizeDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine this with four other different samples in Tane&apos;s Laboratory..
        /// </summary>
        public static string OrganItemDescriptor {
            get {
                return ResourceManager.GetString("OrganItemDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prophecy.
        /// </summary>
        public static string ProphecyKeyword {
            get {
                return ResourceManager.GetString("ProphecyKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality:.
        /// </summary>
        public static string QualityDescriptor {
            get {
                return ResourceManager.GetString("QualityDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity:.
        /// </summary>
        public static string RarityDescriptor {
            get {
                return ResourceManager.GetString("RarityDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeemer Item.
        /// </summary>
        public static string RedeemerItem {
            get {
                return ResourceManager.GetString("RedeemerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements:.
        /// </summary>
        public static string RequirementsDescriptor {
            get {
                return ResourceManager.GetString("RequirementsDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaper Item.
        /// </summary>
        public static string ShaperItem {
            get {
                return ResourceManager.GetString("ShaperItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sockets:.
        /// </summary>
        public static string SocketsDescriptor {
            get {
                return ResourceManager.GetString("SocketsDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior.
        /// </summary>
        public static string SuperiorPrefix {
            get {
                return ResourceManager.GetString("SuperiorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthesised.
        /// </summary>
        public static string SynthesisedKeyword {
            get {
                return ResourceManager.GetString("SynthesisedKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidentified.
        /// </summary>
        public static string UnidentifiedKeyword {
            get {
                return ResourceManager.GetString("UnidentifiedKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaal.
        /// </summary>
        public static string VaalKeyword {
            get {
                return ResourceManager.GetString("VaalKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warlord Item.
        /// </summary>
        public static string WarlordItem {
            get {
                return ResourceManager.GetString("WarlordItem", resourceCulture);
            }
        }
    }
}
