//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POETradeHelper.ItemSearch.UI.Avalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POETradeHelper.ItemSearch.UI.Avalonia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        public static string AccountNameColumn {
            get {
                return ResourceManager.GetString("AccountNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced query.
        /// </summary>
        public static string AdvancedQuery {
            get {
                return ResourceManager.GetString("AdvancedQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string AgeColumn {
            get {
                return ResourceManager.GetString("AgeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armour.
        /// </summary>
        public static string Armour {
            get {
                return ResourceManager.GetString("Armour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacks per Second.
        /// </summary>
        public static string AttacksPerSecond {
            get {
                return ResourceManager.GetString("AttacksPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance to Block.
        /// </summary>
        public static string ChanceToBlock {
            get {
                return ResourceManager.GetString("ChanceToBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted.
        /// </summary>
        public static string Corrupted {
            get {
                return ResourceManager.GetString("Corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse item rarity..
        /// </summary>
        public static string CouldNotParseRarityExceptionMessage {
            get {
                return ResourceManager.GetString("CouldNotParseRarityExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Strike Chance.
        /// </summary>
        public static string CriticalStrikeChance {
            get {
                return ResourceManager.GetString("CriticalStrikeChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS.
        /// </summary>
        public static string Dps {
            get {
                return ResourceManager.GetString("Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemental DPS.
        /// </summary>
        public static string ElementalDps {
            get {
                return ResourceManager.GetString("ElementalDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Shield.
        /// </summary>
        public static string EnergyShield {
            get {
                return ResourceManager.GetString("EnergyShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evasion.
        /// </summary>
        public static string Evasion {
            get {
                return ResourceManager.GetString("Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armour.
        /// </summary>
        public static string FilterCategory_Armour {
            get {
                return ResourceManager.GetString("FilterCategory_Armour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafted.
        /// </summary>
        public static string FilterCategory_Crafted {
            get {
                return ResourceManager.GetString("FilterCategory_Crafted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enchant.
        /// </summary>
        public static string FilterCategory_Enchant {
            get {
                return ResourceManager.GetString("FilterCategory_Enchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit.
        /// </summary>
        public static string FilterCategory_Explicit {
            get {
                return ResourceManager.GetString("FilterCategory_Explicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractured.
        /// </summary>
        public static string FilterCategory_Fractured {
            get {
                return ResourceManager.GetString("FilterCategory_Fractured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implicit.
        /// </summary>
        public static string FilterCategory_Implicit {
            get {
                return ResourceManager.GetString("FilterCategory_Implicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pseudo.
        /// </summary>
        public static string FilterCategory_Pseudo {
            get {
                return ResourceManager.GetString("FilterCategory_Pseudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        public static string FilterCategory_Weapon {
            get {
                return ResourceManager.GetString("FilterCategory_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp. %.
        /// </summary>
        public static string GemExperiencePercentColumn {
            get {
                return ResourceManager.GetString("GemExperiencePercentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string GemLevelColumn {
            get {
                return ResourceManager.GetString("GemLevelColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified.
        /// </summary>
        public static string Identified {
            get {
                return ResourceManager.GetString("Identified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item level.
        /// </summary>
        public static string ItemLevelColumn {
            get {
                return ResourceManager.GetString("ItemLevelColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item search settings.
        /// </summary>
        public static string ItemSearchSettingsHeader {
            get {
                return ResourceManager.GetString("ItemSearchSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League.
        /// </summary>
        public static string LeagueLabel {
            get {
                return ResourceManager.GetString("LeagueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blighted.
        /// </summary>
        public static string MapBlighted {
            get {
                return ResourceManager.GetString("MapBlighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blight-ravaged.
        /// </summary>
        public static string MapBlightRavaged {
            get {
                return ResourceManager.GetString("MapBlightRavaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increased item quantity.
        /// </summary>
        public static string MapItemQuantity {
            get {
                return ResourceManager.GetString("MapItemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increased item rarity.
        /// </summary>
        public static string MapItemRarity {
            get {
                return ResourceManager.GetString("MapItemRarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increased monster packsize.
        /// </summary>
        public static string MapMonsterPacksize {
            get {
                return ResourceManager.GetString("MapMonsterPacksize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier.
        /// </summary>
        public static string MapTier {
            get {
                return ResourceManager.GetString("MapTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found..
        /// </summary>
        public static string NoItemsFoundText {
            get {
                return ResourceManager.GetString("NoItemsFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in browser.
        /// </summary>
        public static string OpenInBrowser {
            get {
                return ResourceManager.GetString("OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical DPS.
        /// </summary>
        public static string PhysicalDps {
            get {
                return ResourceManager.GetString("PhysicalDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string PriceColumn {
            get {
                return ResourceManager.GetString("PriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable price prediction.
        /// </summary>
        public static string PricePredictionSettingLabel {
            get {
                return ResourceManager.GetString("PricePredictionSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string QualityColumn {
            get {
                return ResourceManager.GetString("QualityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sockets.
        /// </summary>
        public static string Sockets {
            get {
                return ResourceManager.GetString("Sockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Size.
        /// </summary>
        public static string StackSize {
            get {
                return ResourceManager.GetString("StackSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthesised.
        /// </summary>
        public static string Synthesised {
            get {
                return ResourceManager.GetString("Synthesised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward.
        /// </summary>
        public static string Ward {
            get {
                return ResourceManager.GetString("Ward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
    }
}
